# Generated by Django 3.0.7 on 2020-06-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endata',
            fields=[
                ('lang', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('sentence_id', models.CharField(max_length=6)),
                ('word_id', models.CharField(max_length=2)),
                ('word', models.CharField(max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('links', models.CharField(blank=True, max_length=100, null=True)),
                ('morpho', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.CharField(blank=True, max_length=10, null=True)),
                ('phrase', models.CharField(blank=True, max_length=100, null=True)),
                ('grm', models.CharField(blank=True, max_length=100, null=True)),
                ('ner', models.CharField(blank=True, max_length=20, null=True)),
                ('semantic', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'EnData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vndata',
            fields=[
                ('lang', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('sentence_id', models.CharField(max_length=6)),
                ('word_id', models.CharField(max_length=2)),
                ('word', models.CharField(max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('links', models.CharField(blank=True, max_length=100, null=True)),
                ('morpho', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.CharField(blank=True, max_length=10, null=True)),
                ('phrase', models.CharField(blank=True, max_length=100, null=True)),
                ('grm', models.CharField(blank=True, max_length=100, null=True)),
                ('ner', models.CharField(blank=True, max_length=20, null=True)),
                ('semantic', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'VnData',
                'managed': False,
            },
        ),
    ]
