export const FETCH_VI_DATA = "VI_DATA";
export const FETCH_EN_DATA = "EN_DATA";
export const UPLOAD_DATA_LANGUAGE = "UPLOAD_DATA_LANGUAGE";
export const UPDATE_PAGE_NUMBER = "UPDATE_PAGE_NUMBER";
export const RESET_LOADING = "RESET_LOADING";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const LOG_OUT = "LOG_OUT";
