import {
  FETCH_EN_DATA,
  FETCH_VI_DATA,
  UPLOAD_DATA_LANGUAGE,
  UPDATE_PAGE_NUMBER,
  RESET_LOADING,
} from "../Action/type";

const initialState = {
  enData:[{
    "id": 1,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "01",
    "word": "'",
    "lemma": "'",
    "links": "1",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 2,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "02",
    "word": "It",
    "lemma": "it",
    "links": "-",
    "morpho": "it",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 3,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "03",
    "word": "'ll",
    "lemma": "'ll",
    "links": "-",
    "morpho": "-",
    "pos": "MD",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 4,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "04",
    "word": "be",
    "lemma": "be",
    "links": "-",
    "morpho": "be",
    "pos": "VB",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 5,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "05",
    "word": "cheap",
    "lemma": "cheap",
    "links": "13",
    "morpho": "cheap",
    "pos": "JJ",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 6,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "06",
    "word": "at",
    "lemma": "at",
    "links": "-",
    "morpho": "at",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 7,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "07",
    "word": "the",
    "lemma": "the",
    "links": "-",
    "morpho": "the",
    "pos": "DT",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 8,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "08",
    "word": "price",
    "lemma": "price",
    "links": "12",
    "morpho": "price",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 9,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "09",
    "word": "if",
    "lemma": "if",
    "links": "2",
    "morpho": "if",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 10,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "10",
    "word": "it",
    "lemma": "it",
    "links": "3",
    "morpho": "it",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 11,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "11",
    "word": "keeps",
    "lemma": "keep",
    "links": "5,10,11",
    "morpho": "keep",
    "pos": "VBZ",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 12,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "12",
    "word": "the",
    "lemma": "the",
    "links": "-",
    "morpho": "the",
    "pos": "DT",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 13,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "13",
    "word": "family",
    "lemma": "family",
    "links": "8",
    "morpho": "family",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 14,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "14",
    "word": "happy",
    "lemma": "happy",
    "links": "7",
    "morpho": "happy",
    "pos": "JJ",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 15,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "15",
    "word": "!",
    "lemma": "!",
    "links": "14",
    "morpho": "!",
    "pos": ".",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 16,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "01",
    "word": "'",
    "lemma": "'",
    "links": "1",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 17,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "02",
    "word": "Renmin",
    "lemma": "Renmin",
    "links": "2",
    "morpho": "-",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 18,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "03",
    "word": "'",
    "lemma": "'",
    "links": "3",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 19,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "04",
    "word": "means",
    "lemma": "mean",
    "links": "4,5",
    "morpho": "mean",
    "pos": "NNS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 20,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "05",
    "word": "'",
    "lemma": "'",
    "links": "7",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 21,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "06",
    "word": "people",
    "lemma": "people",
    "links": "8",
    "morpho": "people",
    "pos": "NNS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 22,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "07",
    "word": "'",
    "lemma": "'",
    "links": "9",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 23,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "08",
    "word": "and",
    "lemma": "and",
    "links": "10",
    "morpho": "and",
    "pos": "CC",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 24,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "09",
    "word": "'",
    "lemma": "'",
    "links": "11",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 25,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "10",
    "word": "bi",
    "lemma": "bi",
    "links": "12",
    "morpho": "-",
    "pos": "FW",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 26,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "11",
    "word": "'",
    "lemma": "'",
    "links": "13",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 27,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "12",
    "word": "means",
    "lemma": "mean",
    "links": "14,15",
    "morpho": "mean",
    "pos": "NNS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 28,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "13",
    "word": "'",
    "lemma": "'",
    "links": "17",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 29,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "14",
    "word": "currency",
    "lemma": "currency",
    "links": "18",
    "morpho": "currency",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 30,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "15",
    "word": "'",
    "lemma": "'",
    "links": "19",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 31,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "16",
    "word": "or",
    "lemma": "or",
    "links": "20",
    "morpho": "or",
    "pos": "CC",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 32,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "17",
    "word": "'",
    "lemma": "'",
    "links": "21",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 33,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "18",
    "word": "money",
    "lemma": "money",
    "links": "22",
    "morpho": "money",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 34,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "19",
    "word": "'",
    "lemma": "'",
    "links": "23",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 35,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "20",
    "word": ".",
    "lemma": ".",
    "links": "24",
    "morpho": ".",
    "pos": ".",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 36,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "01",
    "word": "Thank",
    "lemma": "thank",
    "links": "1,2",
    "morpho": "thank",
    "pos": "VB",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 37,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "02",
    "word": "you",
    "lemma": "you",
    "links": "3",
    "morpho": "you",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 38,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "03",
    "word": "for",
    "lemma": "for",
    "links": "5",
    "morpho": "for",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 39,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "04",
    "word": "showing",
    "lemma": "showing",
    "links": "-",
    "morpho": "show",
    "pos": "VBG",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 40,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "05",
    "word": "us",
    "lemma": "us",
    "links": "6",
    "morpho": "us",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 41,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "06",
    "word": "your",
    "lemma": "your",
    "links": "12",
    "morpho": "your",
    "pos": "PRP$",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 42,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "07",
    "word": "collection",
    "lemma": "collection",
    "links": "7,8,9,10",
    "morpho": "collection",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 43,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "08",
    "word": "of",
    "lemma": "of",
    "links": "-",
    "morpho": "of",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 44,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "09",
    "word": "painting",
    "lemma": "painting",
    "links": "-",
    "morpho": "painting",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 45,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "10",
    "word": ",",
    "lemma": ",",
    "links": "13",
    "morpho": ",",
    "pos": ",",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 46,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "11",
    "word": "\"",
    "lemma": "\"",
    "links": "14",
    "morpho": "-",
    "pos": "-",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 47,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "12",
    "word": "It",
    "lemma": "it",
    "links": "15",
    "morpho": "it",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 48,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "13",
    "word": "'s",
    "lemma": "be",
    "links": "16",
    "morpho": "be",
    "pos": "VBZ",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 49,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "14",
    "word": "my",
    "lemma": "my",
    "links": "19",
    "morpho": "my",
    "pos": "PRP$",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 50,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "15",
    "word": "privilege",
    "lemma": "privilege",
    "links": "17",
    "morpho": "privilege",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 51,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "16",
    "word": "\"",
    "lemma": "\"",
    "links": "20",
    "morpho": "-",
    "pos": "-",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 52,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "17",
    "word": ".",
    "lemma": ".",
    "links": "21",
    "morpho": ".",
    "pos": ".",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 53,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "01",
    "word": "\"",
    "lemma": "\"",
    "links": "-",
    "morpho": "-",
    "pos": "-",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 54,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "02",
    "word": "Chorus",
    "lemma": "chorus",
    "links": "1,2,8,9",
    "morpho": "chorus",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 55,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "03",
    "word": "Line",
    "lemma": "line",
    "links": "3,4,5,6,11",
    "morpho": "line",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 56,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "04",
    "word": "\"",
    "lemma": "\"",
    "links": "7",
    "morpho": "-",
    "pos": "-",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 57,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "05",
    "word": "is",
    "lemma": "be",
    "links": "10",
    "morpho": "be",
    "pos": "VBZ",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 58,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "06",
    "word": "at",
    "lemma": "at",
    "links": "12",
    "morpho": "at",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 59,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "07",
    "word": "the",
    "lemma": "the",
    "links": "-",
    "morpho": "the",
    "pos": "DT",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 60,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "08",
    "word": "Hartford",
    "lemma": "Hartford",
    "links": "13,14",
    "morpho": "-",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "LOCATION",
    "semantic": "-"
},
{
    "id": 61,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "09",
    "word": "Theater",
    "lemma": "theatre",
    "links": "-",
    "morpho": "theatre",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 62,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "10",
    "word": ",",
    "lemma": ",",
    "links": "-",
    "morpho": ",",
    "pos": ",",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 63,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "11",
    "word": "it",
    "lemma": "it",
    "links": "-",
    "morpho": "it",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 64,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "12",
    "word": "says",
    "lemma": "say",
    "links": "-",
    "morpho": "say",
    "pos": "VBZ",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 65,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "13",
    "word": "here",
    "lemma": "here",
    "links": "-",
    "morpho": "here",
    "pos": "RB",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 66,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "14",
    "word": ".",
    "lemma": ".",
    "links": "15",
    "morpho": ".",
    "pos": ".",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 67,
    "lang": "ED",
    "sentence_id": "000005",
    "word_id": "01",
    "word": "£",
    "lemma": "£",
    "links": "2,3",
    "morpho": "-",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 68,
    "lang": "ED",
    "sentence_id": "000005",
    "word_id": "02",
    "word": "10",
    "lemma": "10",
    "links": "1",
    "morpho": "-",
    "pos": "CD",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 69,
    "lang": "ED",
    "sentence_id": "000005",
    "word_id": "03",
    "word": "will",
    "lemma": "will",
    "links": "-",
    "morpho": "will",
    "pos": "MD",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 70,
    "lang": "ED",
    "sentence_id": "000005",
    "word_id": "04",
    "word": "cover",
    "lemma": "cover",
    "links": "-",
    "morpho": "cover",
    "pos": "VB",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},],
  viData:[{
    "id": 1,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "01",
    "word": "'",
    "lemma": "'",
    "links": "1",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 2,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "02",
    "word": "It",
    "lemma": "it",
    "links": "-",
    "morpho": "it",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 3,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "03",
    "word": "'ll",
    "lemma": "'ll",
    "links": "-",
    "morpho": "-",
    "pos": "MD",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 4,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "04",
    "word": "be",
    "lemma": "be",
    "links": "-",
    "morpho": "be",
    "pos": "VB",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 5,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "05",
    "word": "cheap",
    "lemma": "cheap",
    "links": "13",
    "morpho": "cheap",
    "pos": "JJ",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 6,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "06",
    "word": "at",
    "lemma": "at",
    "links": "-",
    "morpho": "at",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 7,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "07",
    "word": "the",
    "lemma": "the",
    "links": "-",
    "morpho": "the",
    "pos": "DT",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 8,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "08",
    "word": "price",
    "lemma": "price",
    "links": "12",
    "morpho": "price",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 9,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "09",
    "word": "if",
    "lemma": "if",
    "links": "2",
    "morpho": "if",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 10,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "10",
    "word": "it",
    "lemma": "it",
    "links": "3",
    "morpho": "it",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 11,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "11",
    "word": "keeps",
    "lemma": "keep",
    "links": "5,10,11",
    "morpho": "keep",
    "pos": "VBZ",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 12,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "12",
    "word": "the",
    "lemma": "the",
    "links": "-",
    "morpho": "the",
    "pos": "DT",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 13,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "13",
    "word": "family",
    "lemma": "family",
    "links": "8",
    "morpho": "family",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 14,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "14",
    "word": "happy",
    "lemma": "happy",
    "links": "7",
    "morpho": "happy",
    "pos": "JJ",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 15,
    "lang": "ED",
    "sentence_id": "000001",
    "word_id": "15",
    "word": "!",
    "lemma": "!",
    "links": "14",
    "morpho": "!",
    "pos": ".",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 16,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "01",
    "word": "'",
    "lemma": "'",
    "links": "1",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 17,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "02",
    "word": "Renmin",
    "lemma": "Renmin",
    "links": "2",
    "morpho": "-",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 18,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "03",
    "word": "'",
    "lemma": "'",
    "links": "3",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 19,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "04",
    "word": "means",
    "lemma": "mean",
    "links": "4,5",
    "morpho": "mean",
    "pos": "NNS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 20,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "05",
    "word": "'",
    "lemma": "'",
    "links": "7",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 21,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "06",
    "word": "people",
    "lemma": "people",
    "links": "8",
    "morpho": "people",
    "pos": "NNS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 22,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "07",
    "word": "'",
    "lemma": "'",
    "links": "9",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 23,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "08",
    "word": "and",
    "lemma": "and",
    "links": "10",
    "morpho": "and",
    "pos": "CC",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 24,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "09",
    "word": "'",
    "lemma": "'",
    "links": "11",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 25,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "10",
    "word": "bi",
    "lemma": "bi",
    "links": "12",
    "morpho": "-",
    "pos": "FW",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 26,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "11",
    "word": "'",
    "lemma": "'",
    "links": "13",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 27,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "12",
    "word": "means",
    "lemma": "mean",
    "links": "14,15",
    "morpho": "mean",
    "pos": "NNS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 28,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "13",
    "word": "'",
    "lemma": "'",
    "links": "17",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 29,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "14",
    "word": "currency",
    "lemma": "currency",
    "links": "18",
    "morpho": "currency",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 30,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "15",
    "word": "'",
    "lemma": "'",
    "links": "19",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 31,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "16",
    "word": "or",
    "lemma": "or",
    "links": "20",
    "morpho": "or",
    "pos": "CC",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 32,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "17",
    "word": "'",
    "lemma": "'",
    "links": "21",
    "morpho": "'",
    "pos": "POS",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 33,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "18",
    "word": "money",
    "lemma": "money",
    "links": "22",
    "morpho": "money",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 34,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "19",
    "word": "'",
    "lemma": "'",
    "links": "23",
    "morpho": "'",
    "pos": "''",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 35,
    "lang": "ED",
    "sentence_id": "000002",
    "word_id": "20",
    "word": ".",
    "lemma": ".",
    "links": "24",
    "morpho": ".",
    "pos": ".",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 36,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "01",
    "word": "Thank",
    "lemma": "thank",
    "links": "1,2",
    "morpho": "thank",
    "pos": "VB",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 37,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "02",
    "word": "you",
    "lemma": "you",
    "links": "3",
    "morpho": "you",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 38,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "03",
    "word": "for",
    "lemma": "for",
    "links": "5",
    "morpho": "for",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 39,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "04",
    "word": "showing",
    "lemma": "showing",
    "links": "-",
    "morpho": "show",
    "pos": "VBG",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 40,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "05",
    "word": "us",
    "lemma": "us",
    "links": "6",
    "morpho": "us",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 41,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "06",
    "word": "your",
    "lemma": "your",
    "links": "12",
    "morpho": "your",
    "pos": "PRP$",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 42,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "07",
    "word": "collection",
    "lemma": "collection",
    "links": "7,8,9,10",
    "morpho": "collection",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 43,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "08",
    "word": "of",
    "lemma": "of",
    "links": "-",
    "morpho": "of",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 44,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "09",
    "word": "painting",
    "lemma": "painting",
    "links": "-",
    "morpho": "painting",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 45,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "10",
    "word": ",",
    "lemma": ",",
    "links": "13",
    "morpho": ",",
    "pos": ",",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 46,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "11",
    "word": "\"",
    "lemma": "\"",
    "links": "14",
    "morpho": "-",
    "pos": "-",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 47,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "12",
    "word": "It",
    "lemma": "it",
    "links": "15",
    "morpho": "it",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 48,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "13",
    "word": "'s",
    "lemma": "be",
    "links": "16",
    "morpho": "be",
    "pos": "VBZ",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 49,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "14",
    "word": "my",
    "lemma": "my",
    "links": "19",
    "morpho": "my",
    "pos": "PRP$",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 50,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "15",
    "word": "privilege",
    "lemma": "privilege",
    "links": "17",
    "morpho": "privilege",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 51,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "16",
    "word": "\"",
    "lemma": "\"",
    "links": "20",
    "morpho": "-",
    "pos": "-",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 52,
    "lang": "ED",
    "sentence_id": "000003",
    "word_id": "17",
    "word": ".",
    "lemma": ".",
    "links": "21",
    "morpho": ".",
    "pos": ".",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 53,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "01",
    "word": "\"",
    "lemma": "\"",
    "links": "-",
    "morpho": "-",
    "pos": "-",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 54,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "02",
    "word": "Chorus",
    "lemma": "chorus",
    "links": "1,2,8,9",
    "morpho": "chorus",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 55,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "03",
    "word": "Line",
    "lemma": "line",
    "links": "3,4,5,6,11",
    "morpho": "line",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 56,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "04",
    "word": "\"",
    "lemma": "\"",
    "links": "7",
    "morpho": "-",
    "pos": "-",
    "phrase": "-",
    "grm": "-",
    "ner": "-",
    "semantic": "-"
},
{
    "id": 57,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "05",
    "word": "is",
    "lemma": "be",
    "links": "10",
    "morpho": "be",
    "pos": "VBZ",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 58,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "06",
    "word": "at",
    "lemma": "at",
    "links": "12",
    "morpho": "at",
    "pos": "IN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 59,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "07",
    "word": "the",
    "lemma": "the",
    "links": "-",
    "morpho": "the",
    "pos": "DT",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 60,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "08",
    "word": "Hartford",
    "lemma": "Hartford",
    "links": "13,14",
    "morpho": "-",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "LOCATION",
    "semantic": "-"
},
{
    "id": 61,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "09",
    "word": "Theater",
    "lemma": "theatre",
    "links": "-",
    "morpho": "theatre",
    "pos": "NNP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 62,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "10",
    "word": ",",
    "lemma": ",",
    "links": "-",
    "morpho": ",",
    "pos": ",",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 63,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "11",
    "word": "it",
    "lemma": "it",
    "links": "-",
    "morpho": "it",
    "pos": "PRP",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 64,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "12",
    "word": "says",
    "lemma": "say",
    "links": "-",
    "morpho": "say",
    "pos": "VBZ",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 65,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "13",
    "word": "here",
    "lemma": "here",
    "links": "-",
    "morpho": "here",
    "pos": "RB",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 66,
    "lang": "ED",
    "sentence_id": "000004",
    "word_id": "14",
    "word": ".",
    "lemma": ".",
    "links": "15",
    "morpho": ".",
    "pos": ".",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 67,
    "lang": "ED",
    "sentence_id": "000005",
    "word_id": "01",
    "word": "£",
    "lemma": "£",
    "links": "2,3",
    "morpho": "-",
    "pos": "NN",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 68,
    "lang": "ED",
    "sentence_id": "000005",
    "word_id": "02",
    "word": "10",
    "lemma": "10",
    "links": "1",
    "morpho": "-",
    "pos": "CD",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 69,
    "lang": "ED",
    "sentence_id": "000005",
    "word_id": "03",
    "word": "will",
    "lemma": "will",
    "links": "-",
    "morpho": "will",
    "pos": "MD",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},
{
    "id": 70,
    "lang": "ED",
    "sentence_id": "000005",
    "word_id": "04",
    "word": "cover",
    "lemma": "cover",
    "links": "-",
    "morpho": "cover",
    "pos": "VB",
    "phrase": "-",
    "grm": "-",
    "ner": "O",
    "semantic": "-"
},],
  languageUpdated: "",
  currentPage: 1,
  loaded: false,
};

let CorpusReducer = (state = initialState, action) => {
  switch (action.type) {
    case FETCH_EN_DATA:
      state.enData = action.payload;
      return { ...state };
    case FETCH_VI_DATA:
      state.viData = action.payload;
      return { ...state };
    case UPLOAD_DATA_LANGUAGE:
      state.languageUpdated = action.payload;
      return { ...state };
    case UPDATE_PAGE_NUMBER:
      state.currentPage = action.payload;
      return { ...state };
    case RESET_LOADING:
      state.loaded = action.payload;
      return { ...state };
    default:
      return state;
  }
};
export default CorpusReducer;
